### ISSUE TITLE
Rotary encoder is incompatible with pico

### ISSUE THREAD

**Issue by aswarthm** [bharath-reddy07/revahack#2]
I am not able to find a compatible library for interfacing rotary encoder with Raspberry Pi Pico
It would be great if you can find me some repositories demonstrating rotary encoder with pico

**Comment by shishiraiyar** [comment]
Found library [here](https://www.arduino.cc/reference/en/libraries/rp2040-encoder-library/)

**Comment by aswarthm** [comment]
Try this repo it looks good https://github.com/aswarthm/PicoMouse/blob/main/MouseTest.ino

**Comment by aswarthm** [comment]
Issue fixed in #3 
Closing the isue now
